apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: {{ .Values.crd.name }}
  labels:
      app: {{ .Values.labels.app }}
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: {{ .Values.crd.group }}
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: {{ .Values.crd.kind }}
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: {{ .Values.crd.kind }}
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          spec:
            type: object
            properties:
              databaseInfo:
                type: object
                properties:
                  databaseType:
                    type: string
                  databaseName:
                    type: string
                  backupPath: 
                    type: string
                  backupInterval:
                    type: string
                  numCopies:
                    type: integer
                    minimum: 1
                    maximum: 100
                  table:
                    type: string
                  storage:
                    type: string
                    pattern: "^[0-9]+(Gi|Mi|Ki)$"
                  storageClass:
                    type: string
                  baseVersion:
                    type: string
              databaseConnect:
                type: object  
                properties:
                  hostname:
                    type: string
                  port:
                    type: integer
                    minimum: 1
                    maximum: 65535
              adminData:
                type: object
                properties:
                  adminCredentials:
                    type: object
                    properties:
                      admindbName:
                        type: string
                      username:
                        type: string
                      password:
                        type: string
              s3data:
                type: object
                properties:
                  host:
                    type: string
                  bucket:
                    type: string
                  accessKey:
                    type: string
                  secretAccessKey:
                    type: string
                  