apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.name }}
  namespace: {{ .Values.rbac.namespace }}
  labels:
    app: {{ .Values.labels.app }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.rolename }}
  labels:
      app: {{ .Values.labels.app }}
rules:

  ################ rights for monitoring crd, jobs, namespaces and secrets resources
- apiGroups: ["{{ .Values.crd.group }}"]
  resources: ["{{ .Values.crd.kind }}"]
  verbs: ["get", "list", "watch", "update"]

- apiGroups: ["batch"]
  # name ресурса 
  #resourceNames
  resources: ["cronjobs"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]

- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]

- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]

- apiGroups: ["*"]
  resources: ["secrets"]
  #resourceNames: ["usersecret-psql", "superusersecret-psql"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["*"]
  resources: ["jobs"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["*"]
  resources: ["persistentvolumes"]
  verbs: ["create", "get", "watch", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.rolename }}
  labels:
      app: {{ .Values.labels.app }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.rolename }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.name }}
  namespace: {{ .Values.rbac.namespace }}
---
